# Generated by Django 4.1.4 on 2023-02-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Wired', on_delete=django.db.models.deletion.CASCADE, to='phase.category'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.product')),
            ],
        ),
    ]
