# Generated by Django 4.1.4 on 2023-02-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0003_cart_alter_product_category_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='uphone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
